### ISSUE TITLE
Issue on docs: Snoozing Pager duty notifier. 

### ISSUE THREAD

**Issue by linhle123** [axiomhq/docs#126]
Path: /monitor-data/pagerduty

1. 
https://axiom.co/docs/monitor-data/pagerduty#disabling-pagerduty-alert-notifier

This section talks about snoozing a notifier, but language doesn't match the UI so I feel confused about following the direction.

"In the Notifier view, click the Snooze button and specify a specific period you want to snooze your notifier for." --> the button is called 'Disable Notifier'. 

2. 
https://axiom.co/docs/monitor-data/monitors#snooze-a-monitor
"Both monitors and notifiers can be snoozed by clicking the ‘alarm clock’ icon when configuring the monitor or notifier. " --> when I follow this guide, it is unclear what I should do next after clicking on the alarm clock icon. The next action to do to disable a monitor is not clear at all.

**Comment by manototh** [comment]
@linhle123 Thank you very much for this. We have recently restructured this section and I believe your suggestions have been addressed: https://axiom.co/docs/monitor-data/configure-notifiers#disable-notifiers
Please be so kind as to let me know if there is anything still missing. Thanks!
