### ISSUE TITLE
logStreams does not support aggregation

### ISSUE THREAD

**Issue by sumit4way** [axiomhq/docs#90]
Issue: -
- I'm trying to add a log stream chart to my custom dashboard that filters logs based on a condition, like | where ([lambda.name] =~ "my-lambda-function-name"). I also want to include a list of all Lambda function names alongside the chart, so I can click on any of them to view the logs for a specific function.
- When I used this APL query:
```
['my-dataset-name']
| where ['lambda.region'] == "us-east-1" 
| summarize by ['lambda.name'] 
```
- I got an error (as shown in the screenshot).
<img width="554" alt="Screenshot 2024-09-27 145512" src="https://github.com/user-attachments/assets/edaf5055-1471-453c-a7e4-9d4ca3ba6514">

I'm wondering if Axiom allows grouping or aggregating log streams, and if not, is there a workaround for this?

**Comment by thecraftman** [comment]
@sumit4way thanks for the message here, yeah, log stream chart do not support visualization currently; you can do this using the Table dashboard widget or using the timeseries chart, which the chart and results table enabled. 

<img width="1357" alt="Screenshot 2024-11-12 at 13 38 27" src="https://github.com/user-attachments/assets/b55c997c-ae6a-45cb-b060-aa13b5f60b07">
<img width="1355" alt="Screenshot 2024-11-12 at 13 39 04" src="https://github.com/user-attachments/assets/5112009d-254c-421f-bfbf-bc9a5d47c1f7">

In your log stream chart its going to be something like:

<img width="1352" alt="Screenshot 2024-11-12 at 13 39 48" src="https://github.com/user-attachments/assets/ead7ee8e-837e-49b1-a16a-ddcf693ed79f">



Please if you have any more questions, you can send an email to `support@axiom.co` or join our community on Discord here: https://axiom.co/discord Thanks a lot.
